name: stv-docker-build-push
description: Action to build an image from the current directory and push it to an Azure Container Registry

inputs:
  container_registry:
    required: true
    type: string
  image_repository:
    required: true
    type: string
  acr_username:
    required: true
    type: string
  acr_password:
    required: true
    type: string


runs:
  using: "composite"
  steps:
  - name: Docker meta
    id: meta
    uses: docker/metadata-action@v4
    with:
      images: |
        ${{ inputs.container_registry }}/${{ inputs.image_repository }}
      tags: |
        type=ref,event=branch
        type=ref,event=pr
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=semver,pattern={{major}}
        type=sha

  - name: Login to Azure Container Registry
    uses: azure/docker-login@v1
    with:
      login-server: ${{ inputs.container_registry }}
      username: ${{ inputs.acr_username }}
      password: ${{ inputs.acr_password }}

  - name: Cache Docker layers
    uses: actions/cache@v2
    with:
      path: $GITHUB_WORKSPACE/docker
      key: 'docker-$RUNNER_OS-cache'

  - name: Restore Docker cache
    run: |
      if [ -f "$GITHUB_WORKSPACE/docker/cache.tar" ]; then
        docker load -i "$GITHUB_WORKSPACE/docker/cache.tar"
      fi
    shell: bash
    continue-on-error: true

  - name: Build and push
    uses: docker/build-push-action@v4
    with:
      context: .
      push: true
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}

  - name: Save Docker cache
    run: |
      DOCKER_TAG=${DOCKER_METADATA_OUTPUT_TAGS##\n*}
      mkdir -p "$GITHUB_WORKSPACE/docker"
      docker save -o "$GITHUB_WORKSPACE/docker/cache.tar" ${DOCKER_TAG}
    shell: bash
